version: "3"
services: 
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: ScoutCloud2
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  app:
    image: scout-cloud-node
    ports:
      - "13000:3000"
    depends_on:
      - db
